### ISSUE TITLE
Education extraction & Experience extraction is not working properly

### ISSUE THREAD

**Issue by iam-mhaseeb** [OmkarPathak/pyresparser#1]
To make education extraction more robust, let's introduce unigram and bigram extraction of words and match with both upper and lower case.

To make the experience more promising let's pull everything from the experience section and slice paragraphs as experiences.

**Comment by OmkarPathak** [comment]
@iam-mhaseeb nice idea. Let's have it get going

**Comment by iam-mhaseeb** [comment]
Can you get out a basic pull request for it? I can work on it to refine more.

**Comment by iam-mhaseeb** [comment]
@OmkarPathak  Any update on it?
