### ISSUE TITLE
Add documentation in readthedocs

### ISSUE THREAD

**Issue by OmkarPathak** [OmkarPathak/pyresparser#10]
Add the documentation about implementation and features of this library

**Comment by LittleSodium** [comment]
Hey Omkar! I would like to work on this issue. Could you guide me with the specifics?

**Comment by OmkarPathak** [comment]
@LittleSodium thanks for your interest. You can refer this documentation: https://pygorithm.readthedocs.io/en/latest/

Basically we need to document our classes and functions and their usage so that users will be able to work with the library more easily.

**Comment by RodolfoFerro** [comment]
I can work on this. 

I will just wait for @LittleSodium to confirm if grabbing this issue. If not, I can take it. ✌️

**Comment by LittleSodium** [comment]
@OmkarPathak got it! Is it fine if I email you for further questions and queries?
@RodolfoFerro I'll be working on this one :)

**Comment by OmkarPathak** [comment]
@LittleSodium sure you can email me anytime 😄

**Comment by OmkarPathak** [comment]
> I can work on this.
> 
> I will just wait for @LittleSodium to confirm if grabbing this issue. If not, I can take it. ✌️

You can simultaneously work on the same

**Comment by RodolfoFerro** [comment]
No problem, good luck @LittleSodium! ✨ 
Btw, if you're planning to use [MkDocs](https://www.mkdocs.org), I can help. 👍 

Thanks @OmkarPathak !

**Comment by LittleSodium** [comment]
@RodolfoFerro I'm super new to open source and this might just be my first ever actual contribution so any help would be appreciated!

**Comment by RodolfoFerro** [comment]
@LittleSodium 
No problem, first fork this repo into your GitHub user.
Then I would install the requirements and try to test everything. 

Now the contribution part comes. I would:
- [Install MkDocs](https://www.mkdocs.org/#installation)
- Create [a new docs project](https://www.mkdocs.org/#getting-started)
- Build documentation 
- Create a [readthedocs](https://readthedocs.org) account
- Build documentation from repo in [readthedocs](https://readthedocs.org)
- Done!

**Comment by OmkarPathak** [comment]
@RodolfoFerro we can also host Mkdocs on GitHub pages. We can also look into this option
