### ISSUE TITLE
Custom NER Trained set

### ISSUE THREAD

**Issue by sayalraza** [OmkarPathak/pyresparser#21]
Hi, 
I need to know which dataset is used to train the **custom nlp** ?
I understand that it is trained using datatrunks annotation tool but need to know what is the dataset bring used here?
Is it the same dataset of 200 something indeed resumes which is used in the datatrunks website?
Please give me a clarity on that.

**Comment by OmkarPathak** [comment]
@sayalraza  it is already mentioned in README

**Comment by sayalraza** [comment]
Ok. Thank you. And sorry for wasting your time asking something already documented.
