### ISSUE TITLE
Some Skills are Missing 

### ISSUE THREAD

**Issue by jamunakarthik** [OmkarPathak/pyresparser#30]
Some of the items are missing while using pyresparser.
Eg: MongoDB, GCP

**Comment by OmkarPathak** [comment]
@jamunakarthik you can pass your custom skills file to check against. Find more about this here: [https://omkarpathak.in/pyresparser/cli/#specifying_skills_explicitly](https://omkarpathak.in/pyresparser/cli/#specifying_skills_explicitly)
