### ISSUE TITLE
UserWarning: [W031] Model 'en_training' (0.0.0) requires spaCy v2.1 and is incompatible with the current spaCy version (2.3.0)

### ISSUE THREAD

**Issue by Arthur-BW** [OmkarPathak/pyresparser#34]
Hi Omar, 

Question, maybe you can help me out. So I've installed all the packages needed for pyreparser. Eventually I ended up with the newer version of Spacy(2.3.0) and en-core-web-sm(2.3.0), because the older versions gave me some errors while installing(I also tried to install the Requirements.txt in a different virtual environment, but that didn't work either). 

As soon as I try the python command from your "usage" header, I get the following message:
C:\Users\Arthur\Documents\Python\.venv\lib\site-packages\spacy\util.py:271: UserWarning: [W031] Model 'en_training' (0.0.0) requires spaCy v2.1 and is incompatible with the current spaCy version (2.3.0). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)

Any idea on how I can train the Model 'en_training' on version 2.3.0 of Spacy?

Cheers, 

Arthur

**Comment by OmkarPathak** [comment]
@Arthur-BW this looks like a core SpaCy issue. They might have changed their compatible models in newer versions. You could open an issue on SpaCy's repo for getting better responses on this. Thanks.

**Comment by Arthur-BW** [comment]
Cheers, will do.
