### ISSUE TITLE
Reading files from external resources

### ISSUE THREAD

**Issue by jamunakarthik** [OmkarPathak/pyresparser#36]
Basically, the resume parser will read file from local. Is there any way to read files from other than local path.
Eg: S3

**Comment by OmkarPathak** [comment]
@jamunakarthik yes it is possible. Please refer this part of documentation: [https://omkarpathak.in/pyresparser/cli/#parsing_hosted_resumes](https://omkarpathak.in/pyresparser/cli/#parsing_hosted_resumes)

**Comment by jamunakarthik** [comment]
Thank you for the response.

Please help me with the following issues

How to use that CLI in python programming
   eg:
    res = ResumeParser(file_path).get_extracted_data()

**Comment by OmkarPathak** [comment]
@jamunakarthik please refer this code snippet: [https://github.com/OmkarPathak/pyresparser/blob/master/test_name.py#L10](https://github.com/OmkarPathak/pyresparser/blob/master/test_name.py#L10)

**Comment by jamunakarthik** [comment]
Thanks for your response.

But, while trying to access file from S3 Bucket it is showing error even though we provided the correct URL.

eg:
remote_file="https://s3/*/ResumeEngine/Resumes/a.pdf" 

Extracting data from: https://s3/*/ResumeEngine/Resumes/a.pdf
File not found. Please Provide correct URL for resume file.

**Comment by OmkarPathak** [comment]
@jamunakarthik not sure if s2 requires any other lib for accessing static files. Please check on your side for this as this is beyond the scope this repository. Feel free to reopen this issue, if you need anything else on this. Thank You 👍
