### ISSUE TITLE
Build dependency error

### ISSUE THREAD

**Issue by rkapri90** [OmkarPathak/pyresparser#37]
Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python 38\python.exe' 'c:\python 38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\XXX\AppData\Local\Temp\pip-build-env-tbkbkos8\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'cython>=0.25' 'cymem>=2.0.2,<2.1.0' 'preshed>=3.0.2,<3.1.0' 'murmurhash>=0.28.0,<1.1.0' thinc==7.4.1
       cwd: None

and so on............
**Help me out,I'm using python 3.8**

**Comment by OmkarPathak** [comment]
Please elaborate "and so on". It is very hard to interpret above error.

**Comment by rkapri90** [comment]
Actually spacy is causing problem,I'm not able to install it

**Comment by OmkarPathak** [comment]
You then have to open an issue on their repository. Thank you 😄
