### ISSUE TITLE
__init__() got an unexpected keyword argument 'codec'

### ISSUE THREAD

**Issue by Kryotasin** [OmkarPathak/pyresparser#39]
I recently installed pyreparser and ran the code like so:

```
from pyresparser import ResumeParser
data = ResumeParser('r.pdf').get_extracted_data()

```

I keep getting the following error. I think it's a pdfminer error but not sure how to fix it inside pyreparser.
![image](https://user-images.githubusercontent.com/8954568/90322936-7776cf80-df0f-11ea-97d5-84d0e1a42d2a.png)

**Comment by OmkarPathak** [comment]
Hey @Kryotasin  did you try this: https://github.com/pdfminer/pdfminer.six/issues/232

**Comment by Kryotasin** [comment]
> Hey @Kryotasin did you try this: [pdfminer/pdfminer.six#232](https://github.com/pdfminer/pdfminer.six/issues/232)

Yes. Thanks. Sorry about the duplicate issue.
