### ISSUE TITLE
The library does not work for resumes with tables

### ISSUE THREAD

**Issue by devgupta2607** [OmkarPathak/pyresparser#43]
I tried the library on a simple table type resume - [resume.pdf](https://github.com/OmkarPathak/pyresparser/files/5448767/required2.pdf)
but got most of the values as null and also got the name wrong
![Opera Snapshot_2020-10-28_054628_colab research google com](https://user-images.githubusercontent.com/42816087/97375549-21e07b00-18e1-11eb-8872-51ec429f0297.png)

**Comment by OmkarPathak** [comment]
@devgupta2607 yes library does not work with tables. Possible duplicate of #5
