### ISSUE TITLE
using pyresparser by providing string to ResumeParser()

### ISSUE THREAD

**Issue by samacker77** [OmkarPathak/pyresparser#45]
I am using this library to parse job descriptions as they come in email bodies in the form of text. But the ResumeParser() api only allows pdf or doc(x). Can someone suggest how to parse a python string using this?

**Comment by OmkarPathak** [comment]
@samacker77 this request has been in my bucket for a long. I Will try to make it a priority. Thanks

**Comment by TheNLPGuy** [comment]
@OmkarPathak I wanted to check-in, was this fixed? We were hoping to try passing strings as inputs instead of pdf/docs

**Comment by DhavalThkkar** [comment]
Waiting for an update on the same
