### ISSUE TITLE
[MainThread  ] [WARNI]  Tika server returned status: 405

### ISSUE THREAD

**Issue by harshgorjiwala** [OmkarPathak/pyresparser#73]
I tired to do this but it giving me and warning and showing me this error and can not fetch anything

util.py:275: UserWarning: [W031] Model 'en_training' (0.0.0) requires spaCy v2.2 and is incompatible with the current spaCy version (2.3.5). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
2022-08-08 12:16:22,548 [MainThread  ] [WARNI]  Tika server returned status: 405
{'email': None,
 'phone': '',
 'name': '',
 'total_exp': 0,
 'university': [],
 'designition': [],
 'degree': [],
 'skills': ['public', 'css', 'xhtml', 'family', 'div', 'access', 'html'],
 'Companies worked at': []}

**Comment by OmkarPathak** [comment]
@harshgorjiwala your current Spacy version seems to be 2.3.5. Please install a version of en_training that is compatible with spacy 2.3.5 or else you can downgrade your spacy to version 2.2

**Comment by harshgorjiwala** [comment]
@OmkarPathak Thank you so much. I figured it out. It was not working perfectly because it I installed JAVA for better output but as soon as i uninstalled JAVA it start working perfectly.
