### ISSUE TITLE
Parser doesn't get any skills

### ISSUE THREAD

**Issue by nickmedwards** [OmkarPathak/pyresparser#9]
I've been trying to use the parser to fetch skill and experience data from resumes and the parser doesn't get any skills? I've attached the resumes I've been testing with
[Brendan_Herger_Resume.pdf](https://github.com/OmkarPathak/pyresparser/files/3622146/Brendan_Herger_Resume.pdf)
[Game-Programmer-Resume-A.pdf](https://github.com/OmkarPathak/pyresparser/files/3622147/Game-Programmer-Resume-A.pdf)
[Game-Programmer-Resume-B.pdf](https://github.com/OmkarPathak/pyresparser/files/3622148/Game-Programmer-Resume-B.pdf)
[Game-Programmer-Resume-C.pdf](https://github.com/OmkarPathak/pyresparser/files/3622149/Game-Programmer-Resume-C.pdf)
[john_smith.pdf](https://github.com/OmkarPathak/pyresparser/files/3622150/john_smith.pdf)
[Layla_Martin_Resume.pdf](https://github.com/OmkarPathak/pyresparser/files/3622151/Layla_Martin_Resume.pdf)
[resume_Meyer.pdf](https://github.com/OmkarPathak/pyresparser/files/3622152/resume_Meyer.pdf)
[SGresume-1.pdf](https://github.com/OmkarPathak/pyresparser/files/3622153/SGresume-1.pdf)

Any help on this would be super awesome! Thanks!

**Comment by OmkarPathak** [comment]
@nickmedwards you have to edit the https://github.com/OmkarPathak/pyresparser/blob/master/pyresparser/skills.csv file in order to parse skills matching your requirements

**Comment by fraywing** [comment]
I'm curious about this, too. @OmkarPathak do you need to add a header column like you have in the example csv? like `technical skills`? Or can it just be a single column of skills per row?

**Comment by OmkarPathak** [comment]
@fraywing thanks for your interest. I'm currently working on this feature. Next release would be released with this feature.

**Comment by OmkarPathak** [comment]
@fraywing @nickmedwards you can refer latest release [v1.0.5](https://github.com/OmkarPathak/pyresparser/tree/v1.0.5) for this fix :smile:
